//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigeR.YuGiOh.UI.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class CardRendering : global::System.Configuration.ApplicationSettingsBase {
        
        private static CardRendering defaultInstance = ((CardRendering)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CardRendering())));
        
        public static CardRendering Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("665, 55")]
        public global::System.Drawing.Point IconPosition {
            get {
                return ((global::System.Drawing.Point)(this["IconPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78, 78")]
        public global::System.Drawing.Size IconSize {
            get {
                return ((global::System.Drawing.Size)(this["IconSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("680, 149")]
        public global::System.Drawing.Point StarPosition {
            get {
                return ((global::System.Drawing.Point)(this["StarPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81, 149")]
        public global::System.Drawing.Point StarPositionReversed {
            get {
                return ((global::System.Drawing.Point)(this["StarPositionReversed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52, 52")]
        public global::System.Drawing.Size StarSize {
            get {
                return ((global::System.Drawing.Size)(this["StarSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int StarPadding {
            get {
                return ((int)(this["StarPadding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48, 45")]
        public global::System.Drawing.Point TitlePosition {
            get {
                return ((global::System.Drawing.Point)(this["TitlePosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("610, 78")]
        public global::System.Drawing.Size TitleSize {
            get {
                return ((global::System.Drawing.Size)(this["TitleSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public float TitleFontSize {
            get {
                return ((float)(this["TitleFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99, 218")]
        public global::System.Drawing.Point CoverPosition {
            get {
                return ((global::System.Drawing.Point)(this["CoverPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("617, 617")]
        public global::System.Drawing.Size CoverSize {
            get {
                return ((global::System.Drawing.Size)(this["CoverSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81, 846")]
        public global::System.Drawing.Point EditionPosition {
            get {
                return ((global::System.Drawing.Point)(this["EditionPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public float EditionFontSize {
            get {
                return ((float)(this["EditionFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("735, 846")]
        public global::System.Drawing.Point SetPosition {
            get {
                return ((global::System.Drawing.Point)(this["SetPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public float SetFontSize {
            get {
                return ((float)(this["SetFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29, 1125")]
        public global::System.Drawing.Point NumberPosition {
            get {
                return ((global::System.Drawing.Point)(this["NumberPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public float NumberFontSize {
            get {
                return ((float)(this["NumberFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("793, 1125")]
        public global::System.Drawing.Point CopyrightPosition {
            get {
                return ((global::System.Drawing.Point)(this["CopyrightPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public float CopyrightFontSize {
            get {
                return ((float)(this["CopyrightFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65, 881")]
        public global::System.Drawing.Point TypePosition {
            get {
                return ((global::System.Drawing.Point)(this["TypePosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public float TypeFontSize {
            get {
                return ((float)(this["TypeFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65, 916")]
        public global::System.Drawing.Point DescriptionMonsterPosition {
            get {
                return ((global::System.Drawing.Point)(this["DescriptionMonsterPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("681, 160")]
        public global::System.Drawing.Size DescriptionMonsterSize {
            get {
                return ((global::System.Drawing.Size)(this["DescriptionMonsterSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19.5")]
        public float DescriptionFontSize {
            get {
                return ((float)(this["DescriptionFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23.5")]
        public float AtkDefFontSize {
            get {
                return ((float)(this["AtkDefFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("495, 1070")]
        public global::System.Drawing.Point AttackPosition {
            get {
                return ((global::System.Drawing.Point)(this["AttackPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("662, 1070")]
        public global::System.Drawing.Point DefensePosition {
            get {
                return ((global::System.Drawing.Point)(this["DefensePosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65, 883")]
        public global::System.Drawing.Point DescriptionOtherPosition {
            get {
                return ((global::System.Drawing.Point)(this["DescriptionOtherPosition"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("681, 233")]
        public global::System.Drawing.Size DescriptionOtherSize {
            get {
                return ((global::System.Drawing.Size)(this["DescriptionOtherSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public float TitlePadding {
            get {
                return ((float)(this["TitlePadding"]));
            }
        }
    }
}
